# Generated by Django 4.1.3 on 2022-11-20 03:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('amount', models.BigIntegerField(default=0)),
                ('status', models.SmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=0)),
                ('update_status_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_customer.customerauth')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date', models.DateTimeField()),
                ('amount', models.BigIntegerField()),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Failed'), (1, 'Success'), (2, 'Pending')])),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Failed'), (1, 'Success'), (2, 'Pending')])),
                ('ref_id', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.balance')),
            ],
            options={
                'unique_together': {('type', 'ref_id')},
            },
        ),
    ]
